### ISSUE TITLE
Can you add feature for automatic "Use address as entered" ?

### ISSUE THREAD

**Issue by ILOVEYOUNA** [Ataraksia/NeweggBot#1]
Can you add feature for automatic "Use address as entered" ?

**Comment by Ataraksia** [comment]
Can you give me an example of an address that triggers that to pop up?  I've never come across it myself.

**Comment by ILOVEYOUNA** [comment]
https://secure.newegg.com/global/th-en/Common/CheckAddress.aspx?CartID=140%2bKUDE09NUWFHYSZG&checkfrompage=checkoutstep&checkbill=1&backpage=Global&nextpage=https%3a%2f%2fsecure.newegg.com%2fglobal%2fth-en%2fGlobalShopping%2fCheckoutStep3.aspx%3fCartID%3d299%252bKUDE09NUWFHYSZG%26PaymentType%3dSIMPLECHECKOUT%26IsFromCart%3d1%26amexstate%3d0&regionCode=THA

https://prnt.sc/uvnp52

**Comment by ILOVEYOUNA** [comment]
https://prnt.sc/uvnpl1

**Comment by ILOVEYOUNA** [comment]
Now I tested the latest version and facing this issue.
https://prnt.sc/uvnrnn [Stuck on Shipping page]

I'm from Thailand and I using this domain: newegg.com/global/th-en/

**Comment by Ataraksia** [comment]
Alright, I think I can fix that.  Does that page immediately follow the cart page?

**Comment by ILOVEYOUNA** [comment]
> Alright, I think I can fix that. Does that page immediately follow the cart page?

Yes.


1. https://secure.newegg.com/global/th-en/Shopping/ShoppingCart.aspx?Submit=view
Picture: https://prnt.sc/uvo5ft

2. https://secure.newegg.com/global/th-en/Common/CheckAddress.aspx?CartID=884%2bBBFAD6IKTGM9T7S&checkfrompage=checkoutstep&checkbill=1&backpage=Global&nextpage=https%3a%2f%2fsecure.newegg.com%2fglobal%2fth-en%2fGlobalShopping%2fCheckoutStep3.aspx%3fCartID%3d614%252bBBFAD6IKTGM9T7S%26PaymentType%3dSIMPLECHECKOUT%26IsFromCart%3d1%26SkippedSignIn%3d1%26amexstate%3d0&regionCode=THA
Picture: https://prnt.sc/uvnp52
After click " Use address as entered "

3. Payment page [Add CCV2]
Picture: https://prnt.sc/uvo80q

3. Review page / Place order
Picture: https://prnt.sc/uvo752

**Comment by Ataraksia** [comment]
Alright, try that to see if it worked.  Also, if there are issues with the ccv2 there, I'll need you to get me the element source so I can see it's ID.

**Comment by ILOVEYOUNA** [comment]
Still have a problem.
https://prnt.sc/uvoj6a

**Comment by Ataraksia** [comment]
Sorry, it can difficult trying to fix problems that I can't actually test on my end haha.  Try this newest one.

**Comment by ILOVEYOUNA** [comment]
Element Source: https://gofile.io/d/ZO5Red

**Comment by Ataraksia** [comment]
That file gave me an error trying to download it.  So is it still not working for you, then?

**Comment by ILOVEYOUNA** [comment]
Yeah, not work.

**Comment by ILOVEYOUNA** [comment]
Download link: https://filebin.net/131pv0vl5kphr3xr

**Comment by Ataraksia** [comment]
Okay, screw it, I made a new Newegg account with a bad address so I can test this.  Give me a few minutes now, I should be able to get it done now that I can see it.

**Comment by ILOVEYOUNA** [comment]
Wow, thank you so much.

**Comment by Ataraksia** [comment]
Alright, try again, let's see what we get this time.

**Comment by ILOVEYOUNA** [comment]
> Alright, try again, let's see what we get this time.

Tested, now stuck on CVV2 page.

**Comment by Ataraksia** [comment]
Alright, good we're almost done, I expected the cvv2 might be different on your end, can you show me an image of the inspection code for it like you did before?

**Comment by ILOVEYOUNA** [comment]
wait me few min.

**Comment by ILOVEYOUNA** [comment]
<input title="cvv2" data-msg-required="This field is required." data-msg-validatecvv2="Security Code is invalid." type="text" value="" maxlength="4" id="creditCardCVV2" autocomplete="off" class="cvv2Code required validateCVV2" onkeydown="javascript:if(event.keyCode == 13) return false;">

https://filebin.net/1wshudxrig5rvbi8

**Comment by Ataraksia** [comment]
Alright, for some odd reason Newegg uses multiple cvv2 IDs.  I've added this second one, go ahead and try it again.

**Comment by ILOVEYOUNA** [comment]
Tested, after the billing page loaded it shows an error immediately.
https://prnt.sc/uvppk3

**Comment by Ataraksia** [comment]
I need the full error message to see the issue.  Is the cvv2 being loaded properly?

**Comment by ILOVEYOUNA** [comment]
`(node:20412) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `#creditCardCVV2` failed: timeout 500ms exceeded
    at new WaitTask (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:411:34)
    at DOMWorld.waitForSelector (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:319:26)
    at Frame.waitForSelector (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:842:51)
    at Page.waitForSelector (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1322:33)
    at run (D:\Best\mom\run.js:120:14)
(node:20412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Ataraksia** [comment]
and try again

**Comment by ILOVEYOUNA** [comment]
tested, bot added CVV2 but show the error.

`(node:14036) UnhandledPromiseRejectionWarning: Error: No node found for selector: #term
    at Object.exports.assert (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.click (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:273:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (D:\Best\mom\run.js:131:2)
(node:14036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The bot also didn't go to "place order" page
`<a class="button button-primary button-override has-icon-right" href="javascript:Biz.GlobalShopping.CheckOut.continueToReview(1);">
        <i class="button-icon-left"></i>Continue To Order Review<i class="button-icon-right fa fa-caret-right"></i>
    </a>`

**Comment by Ataraksia** [comment]
Ah, yeah I think I know why that is, one sec

**Comment by Ataraksia** [comment]
Alright, attempt #1000 :P

**Comment by Ataraksia** [comment]
err, wait a sec, don't get that one yet

**Comment by Ataraksia** [comment]
alright, now try it

**Comment by ILOVEYOUNA** [comment]
> alright, now try it

Got this error.

`(node:11484) UnhandledPromiseRejectionWarning: Error: No node found for selector: #term
    at Object.exports.assert (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.click (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:273:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (D:\Best\mom\run.js:136:2)
(node:11484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Ataraksia** [comment]
Did it manage to get to the review page?

**Comment by ILOVEYOUNA** [comment]
> Did it manage to get to the review page?

No, it's not. It go to this page.
https://prnt.sc/uvq97x

`(node:20416) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:261:23)    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext._evaluateInternal (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:161:64)
    at async D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:90:30
    at async DOMWorld.$ (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:82:26)
    at async DOMWorld.click (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:272:24)    at async run (D:\Best\mom\run.js:136:2)
(node:20416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ILOVEYOUNA** [comment]
It back to page "Use address as entered"

**Comment by Ataraksia** [comment]
Alright, I have a new idea to resolve things, give me a few minutes

**Comment by Ataraksia** [comment]
Can you link the URL you see when you're at one of the checkout pages, whether it be shipping, checkout, or review

**Comment by ILOVEYOUNA** [comment]
https://secure.newegg.com/global/th-en/GlobalShopping/CheckoutByNeweggPay.aspx?CartID=840%2bBBFAD6IKTGM9T7S&GiftOptionFlag=6&SelectedPay=creditcard

I have to go to sleep now, sorry. I'll keep update tmr.

**Comment by Ataraksia** [comment]
Okay, I think I've got it this time, we'll find out tomorrow

**Comment by ILOVEYOUNA** [comment]
> Still have a problem.
> https://prnt.sc/uvoj6a

Now stuck on this page. using the latest version.

**Comment by ILOVEYOUNA** [comment]
Can you fix this code for me?

`const puppeteer = require('puppeteer')
const config = require('./config.json'); 

async function report (log) {
	currentTime = new Date();
	console.log(currentTime.toString().split('G')[0] + ': ' + log)
}
async function check_cart (page) {
	await page.waitForTimeout(250)
	try {
		await page.waitForSelector('span.amount' , { timeout: 1000 })
		var element = await page.$('span.amount')
		var text = await page.evaluate(element => element.textContent, element);
		if (parseInt(text.split('$')[1]) > config.price_limit) {
			await report("Price exceeds limit, removing from cart")
			var button = await page.$$('button.btn.btn-mini');
			while (true) {
				try {
					await button[1].click()
				} catch (err) {
					break
				}
			}
			return false
		}
		await report("Card in stock, attempting to purchase")
		return true
	} catch (err) {
		await report("Card not in stock")
		await page.waitForTimeout(config.refresh_time * 1000)
		return false
	}
}


async function run () {
	await report("Started")
	const browser = await puppeteer.launch({
        	headless: false,
        	defaultViewport: { width: 1366, height: 768 }
    	})
    	const page = await browser.newPage()
	
	await page.goto('http://newegg.com/global/th-en', { waitUntil: 'networkidle2' })
    	while (true) {
		await page.goto('https://secure.newegg.com/global/th-en/NewMyAccount/AccountLogin.aspx?nextpage=https%3a%2f%2fwww.newegg.com/global/th-en%2f', { waitUntil: 'load' })
		if (page.url().includes('signin')) {
			break;
		} else if (page.url().includes("areyouahuman")) {
			await page.waitForTimeout(1000)
		}
	}
	
	await page.waitForSelector('#labeled-input-signEmail')
    	await page.type('#labeled-input-signEmail', config.email)
	await page.waitForTimeout(500)
	await page.click('button.btn.btn-orange')
	try {
		await page.waitForSelector('#labeled-input-password' , {timeout: 2000})
		await page.type('#labeled-input-password', config.password)
		await page.waitForTimeout(500)
		await page.click('button.btn.btn-orange')
		await page.waitForNavigation({
			waitUntil: 'networkidle2',
		});

	} catch (err) {
		report("Manual authorization code required by Newegg.  This should only happen once.")
		while (page.url().includes('signin'))
		{
			await page.waitForTimeout(500)
		}
	}

	await report("Logged in")
	await report("Checking for card")

	while (true)
	{
		await page.goto('https://secure.newegg.com/global/th-en/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=' + config.item_number, { waitUntil: 'load' })
		if (page.url().includes("ShoppingCart")) {
			var check = await check_cart(page)
			if (check) {
				break
			}
		} else if (page.url().includes("ShoppingItem")) {
			await page.goto('https://secure.newegg.com/global/th-en/Shopping/ShoppingCart.aspx', { waitUntil: 'networkidle2' })
			await page.waitForTimeout(500)
			var check = await check_cart(page)
			if (check){
				break
			}
		} else if (page.url().includes("areyouahuman")) {
			await page.waitForTimeout(1000)
		}
	}
	try {
		await page.goto('javascript:attachDelegateEvent((function(){Biz.GlobalShopping.ShoppingCart.checkOut(\'True\')}))', {timeout: 250})
	} catch (err) {
	}
	
	await page.waitForNavigation({
		waitUntil: 'networkidle2',
	});
		
	try {
		await page.goto("javascript:Biz.Shopping.CheckAddress.UseOrginalAddress('Shipping')" , {timeout: 250})
	} catch (err) {
	}
	
	try {
		await page.goto("javascript:Biz.GlobalShopping.CheckOut.continueToBilling()" , {timeout: 250})
	} catch (err) {
	}
	
	while (true) {
		try {
			await page.waitForSelector('#cvv2Code' , {timeout: 500})
			await page.type('#cvv2Code', config.cv2)
			break
		} catch (err) {
		}
		try {
			await page.waitForSelector('#creditCardCVV2' , {timeout: 500})
			await page.type('#creditCardCVV2', config.cv2)
			break
		} catch (err) {
		}
	}
	
	try {
		await page.goto("javascript:Biz.GlobalShopping.CheckOut.continueToReview(1)" , {timeout: 250})
	} catch (err) {
	}
		
	await page.click('#term')
	if (config.auto_submit == 'true') {
		await page.click('#SubmitOrder')
	}
	await report("Completed purchase")
    	//await browser.close()
}


run()`


Error like this.

`(node:19208) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:261:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext._evaluateInternal (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:161:64)
    at async D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:90:30
    at async DOMWorld.$ (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:82:26)
    at async DOMWorld.click (D:\Best\mom\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:272:24)
    at async run (D:\Best\mom\run.js:143:2)
(node:19208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ILOVEYOUNA** [comment]
`const puppeteer = require('puppeteer')
const config = require('./config.json'); 

async function report (log) {
	currentTime = new Date();
	console.log(currentTime.toString().split('G')[0] + ': ' + log)
}
async function check_cart (page) {
	await page.waitForTimeout(250)
	try {
		await page.waitForSelector('span.amount' , { timeout: 1000 })
		var element = await page.$('span.amount')
		var text = await page.evaluate(element => element.textContent, element);
		if (parseInt(text.split('$')[1]) > config.price_limit) {
			await report("Price exceeds limit, removing from cart")
			var button = await page.$$('button.btn.btn-mini');
			while (true) {
				try {
					await button[1].click()
				} catch (err) {
					break
				}
			}
			return false
		}
		await report("Card in stock, attempting to purchase")
		return true
	} catch (err) {
		await report("Card not in stock")
		await page.waitForTimeout(config.refresh_time * 1000)
		return false
	}
}


async function run () {
	await report("Started")
	const browser = await puppeteer.launch({
        	headless: false,
        	defaultViewport: { width: 1366, height: 768 }
    	})
    	const page = await browser.newPage()
	
	await page.goto('http://newegg.com/global/th-en', { waitUntil: 'networkidle2' })
    	while (true) {
		await page.goto('https://secure.newegg.com/global/th-en/NewMyAccount/AccountLogin.aspx?nextpage=https%3a%2f%2fwww.newegg.com/global/th-en%2f', { waitUntil: 'load' })
		if (page.url().includes('signin')) {
			break;
		} else if (page.url().includes("areyouahuman")) {
			await page.waitForTimeout(1000)
		}
	}
	
	await page.waitForSelector('#labeled-input-signEmail')
    	await page.type('#labeled-input-signEmail', config.email)
	await page.waitForTimeout(500)
	await page.click('button.btn.btn-orange')
	try {
		await page.waitForSelector('#labeled-input-password' , {timeout: 2000})
		await page.type('#labeled-input-password', config.password)
		await page.waitForTimeout(500)
		await page.click('button.btn.btn-orange')
		await page.waitForNavigation({
			waitUntil: 'networkidle2',
		});

	} catch (err) {
		report("Manual authorization code required by Newegg.  This should only happen once.")
		while (page.url().includes('signin'))
		{
			await page.waitForTimeout(500)
		}
	}

	await report("Logged in")
	await report("Checking for card")

	while (true)
	{
		await page.goto('https://secure.newegg.com/global/th-en/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=' + config.item_number, { waitUntil: 'load' })
		if (page.url().includes("ShoppingCart")) {
			var check = await check_cart(page)
			if (check) {
				break
			}
		} else if (page.url().includes("ShoppingItem")) {
			await page.goto('https://secure.newegg.com/global/th-en/Shopping/ShoppingCart.aspx', { waitUntil: 'networkidle2' })
			await page.waitForTimeout(500)
			var check = await check_cart(page)
			if (check){
				break
			}
		} else if (page.url().includes("areyouahuman")) {
			await page.waitForTimeout(1000)
		}
	}
	try {
		await page.goto('javascript:attachDelegateEvent((function(){Biz.GlobalShopping.ShoppingCart.checkOut(\'True\')}))', {timeout: 250})
	} catch (err) {
	}
	
	await page.waitForNavigation({
		waitUntil: 'networkidle2',
	});
		
	try {
		await page.goto("javascript:Biz.Shopping.CheckAddress.UseOrginalAddress('Shipping')" , {timeout: 250})
	} catch (err) {
	}
	
	try {
		await page.goto("javascript:Biz.GlobalShopping.CheckOut.continueToBilling()" , {timeout: 250})
	} catch (err) {
	}
	
	while (true) {
		try {
			await page.waitForSelector('#cvv2Code' , {timeout: 500})
			await page.type('#cvv2Code', config.cv2)
			break
		} catch (err) {
		}
		try {
			await page.waitForSelector('#creditCardCVV2' , {timeout: 500})
			await page.type('#creditCardCVV2', config.cv2)
			break
		} catch (err) {
		}
	}
	
	try {
		await page.goto("javascript:Biz.GlobalShopping.CheckOut.continueToReview(1)" , {timeout: 250})
	} catch (err) {
	}
	
	await page.waitForNavigation({
		waitUntil: 'networkidle2',
	});
	
	try {
		await page.goto("javascript:Biz.Shopping.CheckAddress.UseOrginalAddress('Shipping')" , {timeout: 250})
	} catch (err) {
	}
	
	await page.waitForNavigation({
		waitUntil: 'networkidle2',
	});
		
	await page.click('#term')
	if (config.auto_submit == 'true') {
		await page.click('#SubmitOrder')
	}
	await report("Completed purchase")
    	//await browser.close()
}


run()`


I fixed already. Thank you so much. Bro.
