### ISSUE TITLE
Support for combos?

### ISSUE THREAD

**Issue by jabramsja** [Ataraksia/NeweggBot#16]
Great that this is somewhat resurrected!
Any possibility of adding support for combos on Newegg?
Seems like they more commonly have these up than single items. At least when it comes to rarer stuff like 3080, 5950x cpu...etc.

**Comment by jabramsja** [comment]
Basically, I'm talking about these:
https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4207497

**Comment by Codolophier** [comment]
Could you just use, "Combo.4207497" as the Item # in the configuration file?

**Comment by jabramsja** [comment]
It works:). Thank you!
