### ISSUE TITLE
Seems to not find the browser for some reason

### ISSUE THREAD

**Issue by OmarWazzan** [Ataraksia/NeweggBot#3]
Fri Oct 09 2020 18:43:29 : Started
(node:828499) UnhandledPromiseRejectionWarning: Error: Could not find browser revision latest. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at FirefoxLauncher.launch (/root/NeweggBot/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:222:23)
(node:828499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:828499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Have tried both on a computer and VPS.

Followed steps to install.

**Comment by Ataraksia** [comment]
Yeah it's not seeing Firefox.  Did you run the install with the updated command 'npm install puppeteer -PUPPETEER_PRODUCT=firefox'

**Comment by OmarWazzan** [comment]
> Yeah it's not seeing Firefox. Did you run the install with the updated command 'npm install puppeteer -PUPPETEER_PRODUCT=firefox'

I did, yeah. Also tried a variety of different variations I found online, didn't work either.

**Comment by Ataraksia** [comment]
Do you have any other firefox browsers currently open?  Maybe try closing them.  Honestly, i'm not sure.

**Comment by OmarWazzan** [comment]
> Do you have any other firefox browsers currently open? Maybe try closing them. Honestly, i'm not sure. Also, are you on Windows?

Nope. I am running snatcher on the same VPS though. I'll give it a try with snatcher stopped and see if it works. shouldn't be too long

**Comment by majorglory07** [comment]
Getting same error. MacOS.

**Comment by billbo-yang** [comment]
Same error, ubuntu :(

**Comment by billbo-yang** [comment]
@OmarWazzan @majorglory07 @Ataraksia I got it working on my machine with this command to install firefox: `PUPPETEER-PRODUCT=firefox npm i puppeteer`

**Comment by OmarWazzan** [comment]
> @OmarWazzan @majorglory07 @Ataraksia I got it working on my machine with this command to install firefox: `PUPPETEER_PRODUCT=firefox npm i puppeteer`

That does not fix the issue for me. Have tried that command before, and did again on a different machine, no bueno.

**Comment by majorglory07** [comment]
try `npm i puppeteer-core` and then `PUPPETEER_PRODUCT=firefox npm i puppeteer`
